### ISSUE TITLE
Typo in the wiki?

### ISSUE THREAD

**Issue by Pairman** [PaperMC/velocitypowered.com#35]
Is the "systen" a typo in this paragraph shown below? If so, hope  you can fix it.

https://velocitypowered.com/wiki/users/what-does-velocity-do-for-me/

![Screenshot_20210802-033756_Firefox~2.png](https://user-images.githubusercontent.com/18365163/127783310-00c83cf4-19c8-434b-93e2-7c5724c9b8ed.png)

**Comment by astei** [comment]
Fixed some typos (including this one) in 7988ff9cc

**Comment by Pairman** [comment]
> Fixed some typos (including this one) in 7988ff9cc

Great
