### ISSUE TITLE
"FabricProxy" is no longer maintained

### ISSUE THREAD

**Issue by Kichura** [PaperMC/velocitypowered.com#36]
When reading the Server Compatiblity Wiki page for velocity, The fabric context mentions **FabricProxy** which is no longer maintained and has been replaced with [FabricProxy-Lite](https://www.curseforge.com/minecraft/mc-mods/fabricproxy-lite) since to focus on velocity support only.

It's readme file via FabricProxy itself instead of lite:
![image](https://user-images.githubusercontent.com/68134602/130665297-fcb349d1-80a4-4b72-97ed-da6784a05515.png)

**Comment by astei** [comment]
Fixed
